- name: Install fio (RedHat)
  ansible.builtin.include_tasks: install/RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Install fio (Debian)
  ansible.builtin.include_tasks: install/Debian.yml
  when: ansible_os_family == 'Debian'
