---

- name: Kill fio from PIDfile
  ansible.builtin.command:
    cmd: pkill -F /tmp/fio.pid
  become: true
  failed_when: false
  changed_when: true
  when: inventory_hostname in groups['fs_clients']
