---

_fio_perfkit_agg_io_supported_rw_types:
  - read
  - write
  - randread
  - randwrite

_fio_perfkit_agg_io_fiojobs: >-
  {%- set build_fiojobs = [] -%}
  {%- for bs in fio_perfkit_agg_io.fio_bs_list -%}
  {%- for rw in fio_perfkit_agg_io.fio_rw_list -%}
  {%- set _ = build_fiojobs.append(
    {
    "bs": bs,
    "directory": fio_perfkit_agg_io.fio_directory,
    "runtime": fio_perfkit_agg_io.fio_runtime,
    "numjobs": fio_perfkit_agg_io.fio_numjobs,
    "size": fio_perfkit_agg_io.fio_size,
    "nrfiles": fio_perfkit_agg_io.fio_nrfiles,
    "rw": rw,
    }
  ) -%}
  {%- endfor -%}
  {%- endfor -%}
  {{ build_fiojobs }}

fio_perfkit_agg_io_pre_cleanup: true

fio_perfkit_agg_io_directory: "/tmp/fio-perfkit-agg-io-files"

fio_perfkit_agg_io_output_directory: "{{ fio_perfkit_agg_io_directory }}/output"

fio_perfkit_agg_io_jobfile_directory: "{{ fio_perfkit_agg_io_directory }}/jobfiles"

fio_perfkit_agg_io_plot_output_directory: "{{ fio_perfkit_agg_io_directory }}/plots"

fio_perfkit_agg_io_plot_output_prefix: "{{ ansible_date_time.iso8601_basic_short }}"

fio_perfkit_agg_io_venv_path: "{{ fio_perfkit_agg_io_directory }}/venv"

fio_perfkit_agg_io_venv_requirements:
  - binary==1.0.0
  - cycler==0.11.0
  - fonttools==4.34.0
  - kiwisolver==1.4.3
  - matplotlib==3.5.2
  - mizani==0.7.4
  - numpy==1.23.0
  - packaging==21.3
  - palettable==3.3.0
  - pandas==1.5.0
  - patsy==0.5.2
  - Pillow==9.2.0
  - plotnine==0.9.0
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - pytz==2022.2.1
  - scipy==1.9.1
  - six==1.16.0
  - statsmodels==0.13.2
