- name: Run device tests
  hosts: fs_clients
  gather_facts: true
  tasks:
    - name: Test conncurrent IO to all devices on a host
      ansible.builtin.import_role:
        name: stackhpc.fio_perfkit.fio_perfkit_single_host
      vars:
        fio_perfkit_single_host_config:
          - devices:
              - /dev/vdb
              # - /dev/vdc
            max_numjobs: 4
            bs: 1M
            rw: write
            runtime: 2
            filesize: 2M

    - name: Test conncurrent IO from multiple processes to a single device on a host
      ansible.builtin.import_role:
        name: stackhpc.fio_perfkit.fio_perfkit_single_device
      vars:
        fio_perfkit_single_device_config:
          - device: /dev/vdb
            max_numjobs: 4
            bs: 1M
            rw: write
            runtime: 2
            filesize: 2M

- name: Run filesystem tests
  hosts: fs_clients,control
  gather_facts: true
  tasks:
    - name: Test a mix of read/write IO to a shared filesystem from many clients
      ansible.builtin.import_role:
        name: stackhpc.fio_perfkit.fio_perfkit_fs_mixed_io
      vars:
        fio_perfkit_fs_mixed_io_config:
        # Test the product of fio_bs_list, fio_read_mix and fio_random_mix
        # Ranges for fio_read_mix and fio_random_mix are calculated
          fio_directory: /mnt/scratch # Target directory for fio tests
          fio_runtime: 5 # fio runtime
          fio_numjobs: 2 # fio numjobs
          fio_size: 1M # fio filesize
          fio_nrfiles: 2 # fio nrfiles
          fio_bs_list: # List of blocksizes to test
            - 1M
          fio_read_mix:
            start: 0
            end: 100
            step: 50
          fio_random_mix:
            start: 0
            end: 100
            step: 50

    - name: Test the aggregate performance of a shared filesystem from many clients
      ansible.builtin.import_role:
        name: stackhpc.fio_perfkit.fio_perfkit_fs_aggregate_io
      vars:
        fio_perfkit_fs_aggregate_io_config:
          # Test the product of fio_bs_list and fio_rw_list
          fio_directory: /mnt/scratch # Target directory for fio tests
          fio_runtime: 5 # fio runtime
          fio_numjobs: 2 # fio numjobs
          fio_size: 1M # fio filesize
          fio_nrfiles: 2 # fio nrfiles
          fio_bs_list: # List of blocksizes to test
            - 1M
            - 32k
          fio_rw_list: # List of rw modes to test
            - read
            - write
