---

- name: Install fio
  ansible.builtin.include_role:
    name: fio

- name: Configure benchmark
  ansible.builtin.include_tasks: configure.yml

- name: Run fio jobs and plot result
  ansible.builtin.include_tasks: plot.yml
