---

- name: Remove output directory
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ fio_perfkit_single_device_perf_output_directory }}"
  when:
    - fio_perfkit_single_device_perf_pre_cleanup

- name: Ensure output directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    recurse: true
  loop:
    - "{{ fio_perfkit_single_device_perf_directory }}"
    - "{{ fio_perfkit_single_device_perf_output_directory }}"

- name: Ensure sync directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ fio_perfkit_single_device_perf_sync_directory }}"
    mode: 0755
    recurse: true
  delegate_to: localhost
  run_once: true
