---

_fio_perfkit_single_device_perf_fiojobs: >-
  {%- set build_fiojobs = [] -%}
  {%- for bs in fio_perfkit_single_device_perf.bs_list -%}
  {%- for device in fio_perfkit_single_device_perf.device_list -%}
  {%- for rw in fio_perfkit_single_device_perf.rw_list -%}
  {%- set _ = build_fiojobs.append(
    {
    "bs": bs,
    "device": device,
    "rw": rw,
    "runtime": fio_perfkit_single_device_perf.runtime,
    "filesize": fio_perfkit_single_device_perf.size,
    "max_numjobs": fio_perfkit_single_device_perf.max_numjobs
    }
  ) -%}
  {%- endfor -%}
  {%- endfor -%}
  {%- endfor -%}
  {{ build_fiojobs }}

fio_perfkit_single_device_perf_pre_cleanup: true

fio_perfkit_single_device_perf_directory: "/tmp/fio-perfkit-single-device-performance-files"

fio_perfkit_single_device_perf_sync_directory: "/tmp/fio-perfkit-single-device-performance-files/sync"

fio_perfkit_single_device_perf_output_directory: "{{ fio_perfkit_single_device_perf_directory }}/output"

fio_perfkit_single_device_perf_plot_output_directory: "{{ fio_perfkit_single_device_perf_directory }}/plots"

fio_perfkit_single_device_perf_plot_output_prefix: "{{ ansible_date_time.iso8601_basic_short }}"

fio_perfkit_single_device_perf_venv_path: "{{ fio_perfkit_single_device_perf_directory }}/venv"

fio_perfkit_single_device_perf_venv_requirements:
  - binary==1.0.0
  - cycler==0.11.0
  - fonttools==4.34.0
  - kiwisolver==1.4.3
  - matplotlib==3.5.2
  - numpy==1.23.0
  - packaging==21.3
  - Pillow==9.2.0
  - pyparsing==3.0.9
  - python-dateutil==2.8.2
  - six==1.16.0
