---

- name: Ensure EPEL repository is enabled
  ansible.builtin.package:
    name: "epel-release"
  become: true

- name: Ensure system dependencies are installed
  ansible.builtin.package:
    name:
      - "openmpi"
      - "apptainer"
  become: true

- name: Set mpiexec path fact
  ansible.builtin.set_fact:
    mpiexec_path: "/usr/lib64/openmpi/bin/mpiexec"
