---

- name: Drop filesystem caches
  ansible.builtin.command:
    cmd: >-
      {{ io500_drop_caches_cmd }}
  become: true
  changed_when: true

- name: Run io500 test
  ansible.builtin.command:
    cmd: >-
      {{ mpiexec_path }}
      {{ io500_mpiexec_args }}
      --hostfile {{ io500_test_path }}/hosts
      -np {{ io500_mpiexec_np }}
      singularity exec
      {{ io500_singularity_args }}
      {{ io500_image_uri }}
      /io500
      {{ io500_test_path }}/io500-config.ini
  changed_when: true
  when: inventory_hostname == groups['io500'][0]
