---

- name: Find output files
  ansible.builtin.find:
    paths: "{{ ceph_perftest_output_directory }}"
    recurse: true
    file_type: file
  register: output_files

- name: Set local output directory fact
  ansible.builtin.set_fact:
    local_output_directory: >-
      {{
        ceph_perftest_local_output_directory +
        "/" +
        ceph_perftest_local_output_directory_prefix +
        "." +
        ansible_date_time.iso8601_basic_short
      }}
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: Make output directory
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ hostvars['localhost']['local_output_directory'] }}"
  delegate_to: localhost
  run_once: true

- name: Fetch output files
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ hostvars['localhost']['local_output_directory'] }}/"
    flat: true
  loop: "{{ output_files.files | map(attribute='path') }}"
