---

- name: Ensure output directory is removed
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  when: inventory_hostname in groups['control']
  loop:
    - "{{ fio_perfkit_fs_aggregate_io_jobfile_directory }}"
    - "{{ fio_perfkit_fs_aggregate_io_output_directory }}"

- name: Ensure output directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    recurse: true
  when: inventory_hostname in groups['control']
  loop:
    - "{{ fio_perfkit_fs_aggregate_io_jobfile_directory }}"
    - "{{ fio_perfkit_fs_aggregate_io_output_directory }}"

- name: Ensure fio test directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ fio_perfkit_fs_aggregate_io_config.fio_directory }}"
    recurse: true
  become: true

- name: Template fio config
  ansible.builtin.template:
    src: fio-aggregate-perf.fio.j2
    dest: "{{ fio_perfkit_fs_aggregate_io_jobfile_directory }}/job.{{ idx }}.fio"
    mode: "0755"
  loop: "{{ fio_perfkit_fs_aggregate_io_fiojobs }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in groups['control']
  vars:
    bs: "{{ item.bs }}"
    directory: "{{ item.directory }}"
    runtime: "{{ item.runtime }}"
    numjobs: "{{ item.numjobs }}"
    size: "{{ item.size }}"
    nrfiles: "{{ item.nrfiles }}"
    rw: "{{ item.rw }}"
    jobname: "{{ item.rw }}"

- name: Write fio server hosts file
  ansible.builtin.copy:
    content: |
      {% for host in groups['fs_clients'][: idx + 1] %}
      {% set ipaddr = hostvars[host]['ansible_default_ipv4']['address'] %}
      {{ ipaddr }}
      {% endfor -%}
    dest: "{{ fio_perfkit_fs_aggregate_io_jobfile_directory ~ '/fio.' ~ idx ~ '.hosts' }}"
    mode: "0755"
  loop: "{{ groups['fs_clients'] }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in groups['control']
