---
- name: Run prechecks
  ansible.builtin.include_tasks: prechecks.yml

- name: Install ceph-perftest
  ansible.builtin.include_role:
    name: ceph_perftest

- name: Write fio configuration files
  ansible.builtin.include_tasks: configure.yml

- name: Run fio jobs
  ansible.builtin.include_tasks: run.yml

- name: Plot filesystem performance
  ansible.builtin.include_tasks: plot.yml
  when: inventory_hostname in groups['control']

- name: Retrieve output files
  ansible.builtin.include_role:
    name: ceph_perftest
    tasks_from: fetch_output.yml
  vars:
    ceph_perftest_local_output_directory_prefix: "fio-perfkit.fs-aggregate-io"
    ceph_perftest_output_directory: "{{ fio_perfkit_fs_aggregate_io_output_directory }}"
