---

- hosts: clients,control
  gather_facts: true
  name: Test aggregate filesystem performance
  collections:
    - stackhpc.fio_perfkit
  tasks:
    - name: Test aggregate filesystem performance
      ansible.builtin.include_role:
        name: fs_aggregate_performance
