- hosts: clients,control
  gather_facts: true
  collections:
    - stackhpc.fio_perfkit
  name: Run all playbooks

- name: Run mixed IO playbook
  ansible.builtin.import_playbook: mixed.yml

- name: Run aggregate performance playbook
  ansible.builtin.import_playbook: aggregate.yml
