---

- name: Remove output directory
  ansible.builtin.file:
    state: absent
    path: "{{ item }}"
  loop:
    - "{{ fio_perfkit_agg_io_jobfile_directory }}"
    - "{{ fio_perfkit_agg_io_output_directory }}"
  when:
    - fio_perfkit_agg_io_pre_cleanup
    - inventory_hostname in groups['control']

- name: Ensure output directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    recurse: true
  when: inventory_hostname in groups['control']
  loop:
    - "{{ fio_perfkit_agg_io_jobfile_directory }}"
    - "{{ fio_perfkit_agg_io_output_directory }}"

- name: Ensure fio test directory exists
  ansible.builtin.file:
    state: directory
    path: "{{ fio_perfkit_agg_io.fio_directory }}"
    recurse: true
  become: true

- name: Template fio config
  ansible.builtin.template:
    src: fio-aggregate-perf.fio.j2
    dest: "{{ fio_perfkit_agg_io_jobfile_directory }}/job.{{ idx }}.fio"
    mode: 0755
  loop: "{{ _fio_perfkit_agg_io_fiojobs }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in groups['control']
  vars:
    bs: "{{ item.bs }}"
    directory: "{{ item.directory }}"
    runtime: "{{ item.runtime }}"
    numjobs: "{{ item.numjobs }}"
    size: "{{ item.size }}"
    nrfiles: "{{ item.nrfiles }}"
    rw: "{{ item.rw }}"
    jobname: "{{ item.rw }}"

- name: Write fio server hosts file
  ansible.builtin.copy:
    content: |
      {% for host in groups['clients'][: idx + 1] %}
      {{ host }}
      {% endfor -%}
    dest: "{{ fio_perfkit_agg_io_jobfile_directory ~ '/fio.' ~ idx ~ '.hosts' }}"
    mode: 0755
  loop: "{{ groups['clients'] }}"
  loop_control:
    index_var: idx
  when: inventory_hostname in groups['control']
