---
- name: Fail when unsupported rw mode is supplied
  ansible.builtin.fail:
    msg: "rw must be one of {{ _fio_perfkit_agg_io_supported_rw_types | join(',') }}"
  when: item not in _fio_perfkit_agg_io_supported_rw_types
  loop: "{{ fio_perfkit_agg_io.fio_rw_list }}"
  run_once: true
  delegate_to: localhost
