---

- name: Run fio server
  ansible.builtin.include_role:
    name: fio
    tasks_from: run-server.yml
  when: inventory_hostname in groups['clients']

- name: Get list of fio config files
  ansible.builtin.find:
    paths: "{{ fio_perfkit_agg_io_jobfile_directory }}"
    patterns: '*.fio'
  register: fio_config_files
  when: inventory_hostname in groups['control']

- name: Run fio
  ansible.builtin.command:
    cmd: >-
      fio
      --output={{ fio_perfkit_agg_io_output_directory }}/{{ item.config | basename }}.clients{{ item.hosts }}.json
      --client={{ fio_perfkit_agg_io_jobfile_directory ~ '/fio.' ~ item.hosts ~ '.hosts' }}
      {{ item.config }}
      --output-format=json+
  when: inventory_hostname in groups['control']
  loop: >-
    {%- set fio_cmds = [] -%}
    {%- for hosts in range( groups['clients'] | length ) -%}
    {%- for config in (fio_config_files.files | map(attribute='path')) -%}
    {%- set _ = fio_cmds.append(
      {
        "hosts": hosts,
        "config": config
      }
    ) -%}
    {%- endfor -%}
    {%- endfor -%}
    {{ fio_cmds }}

- name: Stop fio server
  ansible.builtin.include_role:
    name: fio
    tasks_from: stop-server.yml
  when: inventory_hostname in groups['clients']

- name: Get list of fio output files
  ansible.builtin.find:
    paths: "{{ fio_perfkit_agg_io_output_directory }}"
    patterns: '*.json'
  register: fio_output_files
  when: inventory_hostname in groups['control']
